#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors:  Chris A. Poblete <Chris_Poblete@Dell.com>
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}
NODATEDUMP=1
. ${MYPATH}/wsl-functions

usage() {
  ${WSCOLORERR}
  cat <<EOF
USAGE: $MYNAME XMLFilename ResultIndex PropertyName [AttributePattern...]

ResultIndex is 1-based. Specify 0 to search for the last occurrence.
One or two attributes may have the same pattern. For instance, attribute
Name and attribute CreationClassName. The following example helps limit
the response:

This command returns the second instance of a node named 'Selector'
and attribute 'ClassName' or "CreationClassName'
  $ wxmlquery computersystemepr.xml 2 Selector ClassName

This command returns the second instance of a node named 'Selector'
and attribute 'Name'. 
  $ wxmlquery computersystemepr.xml 2 Selector \"Name

Requires: wsl
EOF
  $WSCOLORNORM
  exit 1
}

[ $# -lt 3 ] && usage
fSearchValueOf $@
echo ${PVALUE}

